### ISSUE TITLE
github username: coldpeach2

### ISSUE THREAD

**Issue by coldpeach2** [bcb420-2021/Student_Wiki#10]
:)

**Comment by risserlin** [comment]
Was this closed in error?  Are you a student in bcb420-2021 looking for an account? If so then please post your student names as well.

**Comment by coldpeach2** [comment]
oops, that was an error. Yes, I am a student looking for an account for Areej Negm.

**Comment by risserlin** [comment]
Added to the organization.  Create repo - https://github.com/bcb420-2021/Areej_Negm
