### ISSUE TITLE
Can't add myself into Wiki

### ISSUE THREAD

**Issue by juliana-chu** [bcb420-2021/Student_Wiki#27]
Hello, 
I cannot add my repo and wiki url into wiki through Rstudio, it said I don't have the permission. I wonder how can I add myself into the wiki section? Please help!

**Comment by risserlin** [comment]
you should have received multiple invites to github.  (organization, team and repo).  In order to make changes everywhere you need to accept all these invitations.  Please check your spam folder if you didn't receive these emails.
