### ISSUE TITLE
add to bcb420-2021 organization

### ISSUE THREAD

**Issue by Tracyt1117** [bcb420-2021/Student_Wiki#6]
My github username is: Tracyt1117

**Comment by yu-kuai** [comment]
My github username is: quick2063706271

**Comment by risserlin** [comment]
added to the bcb420 organization - repo at - https://github.com/bcb420-2021/Yutong_Chen for Tracyt1117

**Comment by risserlin** [comment]
added to bcb420 organization - repo at https://github.com/bcb420-2021/Kuai_Yu for quick2063706271
